env:
    HOME: /root
    MY_SECRET: ENCRYPTED[b013aad8d38fcf8c0498ce00a041d3eb73882f01c4161fb06ed4e16b40dda9d8d8fdcbe54534f195b65bab3de127aaa2]        

container:
  image: golang:latest

task:
  name: Test
  alias: Tests
  aws_credentials:
    role_arn: arn:aws:iam::438465165216:role/cirrus-ci-oidc-Role-K5h641pZ0chJ
    role_session_name: cirrus1
    region: us-west-2
  ec2_instance:
    image: ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-*
    architecture: amd64
    region: us-west-2
    type: t3a.micro
  install_docker_script:
    - sleep 300
    - sudo snap install docker
  test_script:
    - wget --no-verbose -O - https://go.dev/dl/go1.21.4.linux-arm64.tar.gz | tar -C /usr/local -xz
    - export PATH=$PATH:/usr/local/go/bin
    - go build -o vetu cmd/vetu/main.go
    - export PATH=$PATH:$(pwd)
    - sudo setcap cap_net_raw,cap_net_admin+eip vetu
    - go test -v -tags integration ./...
  env:
    HOME: /root
    MY_SECRET: ENCRYPTED[b013aad8d38fcf8c0498ce00a041d3eb73882f01c4161fb06ed4e16b40dda9d8d8fdcbe54534f195b65bab3de127aaa2] 
